import { UserLdap } from './user-ldap';

export const LDAP_USERS: UserLdap[] = [
  {
    id: 1,
    login: 'test.v1',
    nom: 'V1',
    prenom: 'Test',
    nomComplet: 'V1 Test',
    motDePasse: null,
    mail: 'test.v1@epsi.fr',
    role: 'ROLE_USER',
    employeNumero: 1234,
    employeNiveau: 120,
    dateEmbauche: '2020-01-01',
    publisherId: 1,
    active: true,
  },
  {
    id: 2,
    login: 'test.v2',
    nom: 'V2',
    prenom: 'Test',
    nomComplet: 'V2 Test',
    motDePasse: null,
    mail: 'test.v2@epsi.fr',
    role: 'ROLE_USER',
    employeNumero: 2234,
    employeNiveau: 220,
    dateEmbauche: '2020-02-01',
    publisherId: 2,
    active: true,
  },
  {
    id: 3,
    login: 'test.v3',
    nom: 'V3',
    prenom: 'Test',
    nomComplet: 'V3 Test',
    motDePasse: null,
    mail: 'test.v3@epsi.fr',
    role: 'ROLE_USER',
    employeNumero: 3334,
    employeNiveau: 330,
    dateEmbauche: '3030-03-01',
    publisherId: 3,
    active: true,
  },
  {
    id: 4,
    login: 'test.v4',
    nom: 'V4',
    prenom: 'Test',
    nomComplet: 'V4 Test',
    motDePasse: null,
    mail: 'test.v4@epsi.fr',
    role: 'ROLE_USER',
    employeNumero: 4434,
    employeNiveau: 440,
    dateEmbauche: '4040-04-01',
    publisherId: 4,
    active: true,
  },
  {
    id: 5,
    login: 'test.v5',
    nom: 'V5',
    prenom: 'Test',
    nomComplet: 'V5 Test',
    motDePasse: null,
    mail: 'test.v5@epsi.fr',
    role: 'ROLE_USER',
    employeNumero: 5534,
    employeNiveau: 550,
    dateEmbauche: '5050-05-01',
    publisherId: 5,
    active: true,
  },
  {
    id: 6,
    login: 'test.v6',
    nom: 'V6',
    prenom: 'Test',
    nomComplet: 'V6 Test',
    motDePasse: null,
    mail: 'test.v6@epsi.fr',
    role: 'ROLE_USER',
    employeNumero: 6634,
    employeNiveau: 660,
    dateEmbauche: '6060-06-01',
    publisherId: 6,
    active: true,
  },
];
